include: package:pedantic/analysis_options.1.8.0.yaml

linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_void_to_null
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - constant_identifier_names
    - directives_ordering
    - empty_constructor_bodies
    - file_names
    - flutter_style_todos
    - join_return_with_assignment
    - library_prefixes
    - lines_longer_than_80_chars
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    # - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_const
    - recursive_getters
    - unawaited_futures
    - type_init_formals
    # - public_member_api_docs
    - prefer_spread_collections
    - unnecessary_null_in_if_null_operators
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - use_function_type_syntax_for_parameters
    - sort_child_properties_last
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
    - void_checks
    - unnecessary_this
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_full_hex_values_for_flutter_colors
    - unnecessary_overrides
    - unnecessary_parenthesis
    - sort_unnamed_constructors_first
    - type_annotate_public_apis


analyzer:
  exclude: 
    - lib/generated/i18n.dart
    - lib/**.g.dart
  errors:
    prefer_conditional_assignment: error
    always_declare_return_types: error
    type_annotate_public_apis: error
    avoid_positional_boolean_parameters: error
    always_put_required_named_parameters_first: error
    avoid_renaming_method_parameters: error
    avoid_returning_null_for_void: error
    avoid_returning_null: warning
    prefer_null_aware_operators: error
    provide_deprecation_message: error
    prefer_spread_collections: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_null_aware_assignments: error
    prefer_typing_uninitialized_variables: error
    avoid_single_cascade_in_expression_statements: error
    avoid_unused_constructor_parameters: error
    cascade_invocations: error
    empty_constructor_bodies: error
    use_string_buffers: error
    flutter_style_todos: error
    recursive_getters: error
    join_return_with_assignment: error
    library_prefixes: error
    lines_longer_than_80_chars: error
    non_constant_identifier_names: error
    null_closures: error
    one_member_abstracts: error
    only_throw_errors: error
    overridden_fields: error
    prefer_inlined_adds: error
    prefer_iterable_whereType: error
    prefer_interpolation_to_compose_strings: error
    prefer_adjacent_string_concatenation: error
    prefer_asserts_in_initializer_lists: error
    prefer_generic_function_type_aliases: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    
